#!/bin/bash

arp -n |awk '{print $1}' |grep ^'10.\|172.16\|192.168' |while read ip; do
  docker exec -i nmap nmap -p445 --script /data/nmap/smb-vuln-ms17-010 $ip >> smb-vuln.`date +%Y%m%d`.log &
  sleep 1
done

