#!/bin/bash

docker exec -it web-stack-mysql-db-2 mysql -e "SHOW STATUS LIKE 'wsrep_local%'"
docker exec -it web-stack-mysql-db-2 mysql -e "SHOW STATUS LIKE 'wsrep_cluster%'"
docker exec -it web-stack-mysql-db-2 mysql -e "SHOW STATUS LIKE 'wsrep_ready%'"

