#!/bin/bash

docker exec -it mysql-db-3 mysql -e "SHOW STATUS LIKE 'wsrep_local%'"
docker exec -it mysql-db-3 mysql -e "SHOW STATUS LIKE 'wsrep_cluster%'"
docker exec -it mysql-db-3 mysql -e "SHOW STATUS LIKE 'wsrep_ready%'"

