#!/bin/bash
exec 2>&1

export PATH=$PATH:/usr/local/bin
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
source $SCRIPTPATH/../../../.utils/bash/utils
source $SCRIPTPATH/../../../.utils/bash/docker
source $SCRIPTPATH/lib/backup
source $SCRIPTPATH/lib/slack

function main (){
  mkdir -p /mnt/nas/backup/gitlab

  # remove gitlab backup older then 5 days
  find /mnt/nas/backup/gitlab -mtime +4 -exec rm {} \;

  # remove redmine backup older then 5 days
  find /mnt/nas/backup/redmine -mtime +4 -exec rm {} \;

  # move gitlab backup to nas
  DIR=/opt/web-stack/apps/gitlab/data/gitlab/gitlab/backups
  if [ "$(ls -A $DIR)" ]; then
    mv $DIR/*.tar /mnt/nas/backup/gitlab/ &>/dev/null || true
  fi

  # move redmine backup to nas
  DIR=/opt/web-stack/apps/redmine/data/redmine/backups
  if [ "$(ls -A $DIR)" ]; then
    mv $DIR/*.tar /mnt/nas/backup/redmine/ &>/dev/null || true
  fi

  # backup harbor
  rsync -rvh /opt/web-stack/apps/harbor/data /mnt/nas/backup/harbor --delete

  # backup testlink
  rsync -rvh /opt/web-stack/apps/testlink/data /mnt/nas/backup/testlink --delete

  # clean slack msg
  slack_clean_msg Slack_API_KEY_Here droneci 2

  # remove no-trunc docker img
  docker images --no-trunc | grep none | awk '{print $3}' | xargs docker rmi -f
  docker rmi $(docker images |grep 'thingspro-server')

}

main $1

