version: "3"

services:
  mysql-db-1:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: web-stack/percona-galera
    container_name: mysql-db-1
    hostname: mysql-db-1
    env_file:
      - ../../../.env/cache.env
      - ../../../.env/config.env
      - ../../../.env/deploy.env
    environment:
      # first bootstrap node
      BOOTSTRAP: 1
      # first node host name
      # CLUSTER_MEMBERS: db-03
      # DEBUG: 1
      HOST: mysql-db-1
    extra_hosts:
      - mysql-db-1:172.16.21.211
      - mysql-db-2:172.16.21.212
      - mysql-db-3:172.16.21.206
    ports:
      - 3306:3306
      - 4444:4444
      - 4567:4567
      - 4568:4568
    volumes:
      - ./data/shared:/data/shared:rw
      - ./data/mysql:/var/lib/mysql:rw
networks:
  default:
    external:
      name: web-stack
