version: "3"

services:
  nginx:
    # restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: web-service/nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80/tcp"
    volumes:
      - ./data/nginx/conf:/etc/nginx/conf.d:rw
      - ./data/nginx/sites-enabled:/etc/nginx/sites-enabled:rw
      - ./data/nginx/log:/var/log/nginx:rw
      - ./data/www:/var/www:rw
networks:
  default:
    external:
      name: web-service
