version: "3"

services:
  mysql-db-3:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: web-service/percona-galera
    container_name: mysql-db-3
    hostname: mysql-db-3
    network_mode: host
    environment:
      # first bootstrap node
      # BOOTSTRAP: 1
      # first node host name
      CLUSTER_MEMBERS: mysql-db-1
      # DEBUG: 1
      MYSQL_PASS: Moxa89191230
      REP_PASS: replicate
      HOST: mysql-db-3
      SERVICE_DISCOVERY: env
    extra_hosts:
      - mysql-db-1:172.16.21.211
      - mysql-db-2:172.16.21.212
      - mysql-db-3:172.16.21.206
    ports:
      - 3306:3306
      - 4444:4444
      - 4567:4567
      - 4568:4568
    volumes:
      - ./data/shared:/data/shared:rw
      - ./data/mysql:/var/lib/mysql:rw
